import {StyleSheet} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    backgroundColor: "#FFFFFF",
    paddingBottom: 65,
    paddingHorizontal: 30,
    position: "relative",
  },
  pageCover: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 50,
    paddingHorizontal: 0,
    position: "relative",
  },
  header: {
    borderBottomWidth: 4,
    borderBottomColor: "#823b0b",
    textTransform: "uppercase",
    borderBottomStyle: "solid",
    marginBottom: 12,
    marginTop: 32,
    lineHeight: 1.5,
    paddingBottom: 8,
    fontSize: 10,
  },
  footer: {
    borderTopWidth: 4,
    borderTopColor: "#823b0b",
    borderTopStyle: "solid",
    marginBottom: 12,
    marginTop: 32,
    position: "absolute",
    display: "flex",
    flexDirection: "row",
    bottom: 0,
    width: "100%",
    left: 0,
    right: 0,
    marginHorizontal: 60,
    textAlign: "left",
    lineHeight: 1.5,
    paddingTop: 8,
    fontSize: 10,
  },
  footerCover: {
    position: "absolute",
    bottom: 48,
    width: "100%",
    left: 0,
    right: 0,
    marginHorizontal: 60,
    textAlign: "center",
    lineHeight: 1.5,
    fontSize: 14,
  },
  footerCoverText: {
    paddingVertical: 12,
    width: "60%",
    borderBottomLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: "green",
    marginHorizontal: "auto",
  },
  title: {
    fontWeight: "bold",
    textTransform: "uppercase",
    color: "white",
    backgroundColor: "#9dca87",
    padding: 14,
    marginBottom: 12,
    borderRadius: 6,
    borderColor: "#8bbc6a",
    borderWidth: 2,
  },
  body: {
    fontWeight: 400,
    textAlign: "justify",
    color: "black",
    fontSize: 14,
    fontFamily: "Times-Roman",
    lineHeight: 1.5,
    textIndent: 16,
    marginTop: 16,
  },
  detailContainer: {
    flexDirection: "row",
  },
  dedicationBody: {
    paddingVertical: 40,
    backgroundColor: "lightgrey",
    width: "100%",
    borderRadius: 8,
    // fontFamily: "arial",
    borderWidth: 8,
    borderColor: "grey",
    borderStyle: "solid",
  },
  column: {
    paddingHorizontal: 16,
  },
  paragraph: {
    marginBottom: 12,
  },
  line: {
    textAlign: "left",
    fontSize: 12,
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 12,
  },
  h1: {
    fontWeight: 600,
    fontSize: 12,
    flexGrow: 1,
  },
});

export default styles;
